version: 2
jobs:
   build:
     docker:
       - image: circleci/node:4.8.2
     steps:
       - checkout
       - run: echo "starting build"

   acceptance_test_1:
     docker:
       - image: circleci/node:4.8.2
     steps:
       - checkout
       - run: echo "starting test 1"

   acceptance_test_2:
     docker:
       - image: circleci/node:4.8.2
     steps:
       - checkout
       - run: echo "starting test 2"

   acceptance_test_3:
     docker:
       - image: circleci/node:4.8.2
     steps:
       - checkout
       - run: echo "starting test 3"

   acceptance_test_4:
     docker:
       - image: circleci/node:4.8.2
     steps:
       - checkout
       - run: echo "starting test 4"

   deploy:
     docker:
       - image: circleci/node:4.8.2
     steps:
       - checkout
       - run: echo "starting deploy"


workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - acceptance_test_1:
          requires:
            - build
      - acceptance_test_2:
          requires:
            - build
      - acceptance_test_3:
          requires:
            - build
      - acceptance_test_4:
          requires:
            - build
      - deploy:
          requires:
            - acceptance_test_1
            - acceptance_test_2
            - acceptance_test_3
            - acceptance_test_4
